Update Traditional Chinese for v15
shedaniel/ClothConfig pull request #281
Opened 2024-08-17 21:39 UTC by yichifauzi

Update Traditional Chinese localization for v15
From https://github.com/shedaniel/cloth-config/pull/216 by @notlin4

2024-08-18 06:59 UTC, notlin4 requested changes

2024-08-18 06:59 UTC, notlin4 commented on common/src/main/resources/assets/cloth-config2/lang/zh_tw.json
> +    "option.cloth-config.scrollStep": "滾動距離",
```suggestion
    "option.cloth-config.scrollStep": "捲動距離",
```

2024-08-18 06:59 UTC, notlin4 commented on common/src/main/resources/assets/cloth-config2/lang/zh_tw.json
> +    "text.cloth-config.testing.3": "點選此處開啟 Minecraft 選項檔案（無特殊原因）"
```suggestion
    "text.cloth-config.testing.3": "按這裡開啟 Minecraft 選項檔案（無特殊原因）"
```

2024-08-18 06:59 UTC, notlin4 commented on common/src/main/resources/assets/cloth-config2/lang/zh_tw.json
> +    "text.cloth-config.quit_discard": "退出並放棄變更",
```suggestion
    "text.cloth-config.quit_discard": "離開並放棄變更",
```

2024-09-16 16:49 UTC, shedaniel approved these changes

2024-09-16 16:55 UTC, merged

2024-09-16 16:55 UTC, shedaniel commented
十分感謝！:D